---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--no-warnings]

  - repo: https://github.com/aristanetworks/j2lint
    rev: v1.2.0
    hooks:
      - id: j2lint
        args: [template, --ignore, S6]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
