---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # v1.38.0
    hooks:
      - id: yamllint
        args: [--no-warnings]

  - repo: https://github.com/aristanetworks/j2lint
    rev: ba3ae401e723b8e359ea675274d6733340f96582  # v1.2.0
    hooks:
      - id: j2lint
        args: [template, --ignore, S6]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # v0.15.12
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
