---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install dependencies
        run: uv sync --group dev
      - name: Generate templates for linting
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          uv run copier copy --defaults --vcs-ref=HEAD . test_template
      - name: Lint code
        run: |
          uv run j2lint template --ignore S6
          uv run yamllint . --no-warnings
      - name: Run Format and Lint Checks
        run: |
          uv run ruff check .
          uv run ruff format --check .
      - name: Run tests
        run: |
          uv run pytest
          PYTHONPATH=test_template uv run pytest test_template/tests
